config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users, controllers: {registrations: "registrations"}
  root to: "pages#home"
  resources :users, only: [:show, :edit, :update]
  resources :bookings, only: [:show, :new, :create, :index, :delete, :update]
  resources :activities
  mount Attachinary::Engine => "/attachinary"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  has_many :bookings
  validates :name, presence: true, inclusion: {in: %w( Cuisine Informatique Conversation Lecture)}
  validates :starting_time, presence: true
  validates :end_time, presence: true
  validates :price, presence: true

  def self.search(query)
    if query[:name] == "" && query[:starting_time] == "" && query[:end_time] == ""
      all
    elsif query[:starting_time] == "" && query[:end_time] == ""
      where("name = ?", query[:name])
    elsif query[:name] == "" && query[:end_time] == ""
      where("starting_time <= ?", query[:starting_time].to_date)
    elsif query[:name] == "" && query[:starting_time] == ""
      where("end_time >= ?", query[:end_time].to_date)
    elsif query[:end_time] == ""
      where("name = ? AND starting_time <= ?", query[:name], query[:starting_time].to_date)
    elsif query[:name] == ""
      where("starting_time <= ? AND end_time >= ?", query[:starting_time].to_date, query[:end_time].to_date)
    elsif query[:starting_time] == ""
      where("name = ? AND end_time >= ?", query[:name], query[:end_time].to_date)
    else
      where("name = ? AND starting_time <= ? AND end_time >= ?", query[:name], query[:starting_time].to_date, query[:end_time].to_date)
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities, dependent: :destroy
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  # validates :name, presence: true
  # validates :surname, presence: true
  # validates :birthdate, presence: true

  has_attachment :photo

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :destroy, :update]
  skip_before_action :authenticate_user!, only: :index

  def index
    @booking = Booking.new
    if params[:search]
      @search = params[:search]
      if params[:search][:address] != ""
        @users = User.near(params[:search][:address], 20)
        @users_id = []
        @users.each do |user|
          @users_id << user.id
        end
        @activities = Activity.search(params[:search]).where(user_id: @users_id)
      else
        @activities = Activity.search(params[:search])
      end
    else
      @activities = Activity.all
    end
  end

  def show
    @search = params[:search]
    @booking = Booking.new
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = current_user.activities.new(activity_params)
    if @activity.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def destroy
    @activity.delete
    redirect_to user_path(current_user)
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :starting_time, :end_time, :price, :pictogram_link, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = current_user.bookings
    @my_activities = current_user.activities
    @my_bookings = Booking.joins(:activity).where("activities.user_id = ?", current_user.id)
    # raise
 end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path(@bookings)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to root_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :activity_id, :accepted)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_sign_up_path_for(resource)
    edit_user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to edit_user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    @user.save
    redirect_to user_path(@user)
  end

  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # DELETE /restaurants/1.json
  # def destroy
  #   @restaurant.destroy
  #   respond_to do |format|
  #     format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
  def user_params
    params.require(:user).permit(:name, :address, :surname, :description, :photo, :birthdate)
  end

  def set_user
    @user  = User.find(params[:id])
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_form.html.erb
<div class="page-wrapper">
  <div class="page-container">
    <div class="container form">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-sm-offset-3">
          <%= simple_form_for (@activity) do |f| %>
            <%= f.error_notification %>
            <h1 class="text-center form-ro"><%= "Détails de la mission" %></h1>
            <%= f.input :name, collection: ["Cuisine", "Informatique", "Conversation", "Lecture"], label: "Nom" %>
            <%= f.input :starting_time, as: :string, input_html: { class: 'datepicker'}, label: "Date de démarrage" %>
            <%= f.input :end_time, as: :string, input_html: { class: 'datepicker'}, label: "Date de fin" %>
            <%= f.input :price, label: "Rémunération" %>
            <%= f.input :description, label: "Description" %>
            <%= f.button :submit, class: "btn btn-home", style: "width: 100%", value: "Créer une activité" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<%= render 'form' %>

app/views/activities/index.html.erb
<div class="page-wrapper">
  <div class="page-container">
  <h1 class="text-center title">Activités disponibles</h1>
    <div class="container">
      <% @activities.each do |activity| %>
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 ">
          <div class="row">
            <div class="booking" >
              <div class='text-center booking-body col-xs-2 col-xs-offset-1 '>
                <div>
                  <h3>
                   <% if activity.name === "Cuisine" %>
                    <h3 class="text-center"><i class="fa fa-cutlery"></i> <%= activity.name %></h3>
                  <% elsif activity.name === "Informatique" %>
                    <h3 class="text-center"><i class="fa fa-laptop"></i> <%= activity.name %></h3>
                  <% elsif activity.name === "Conversation" %>
                    <h3 class="text-center"><i class="fa fa-commenting-o"></i> <%= activity.name %></h3>
                  <% else %>
                    <h3 class="text-center"><i class="fa fa-book"></i> <%= activity.name %></h3>
                  <% end %>
                  </h3>
                  <p><%= activity.user.address %></p>
                  <p><strong><%= activity.price %>€</strong></p>
                </div>
                <div class="photo col-xs-2 col-xs-offset-1 ">
                  <% if activity.user.photo?%>
                    <%= cl_image_tag activity.user.photo.path, width: 100, height: 100, crop: :fill %>
                  <% else %>
                    <%= image_tag "papy_marcel.jpg", width: 100, height: 100, crop: :fill %>
                  <% end %>
                  <p class="text-center"><%= activity.user.name %></p>
                </div>
                <div class="col-xs-2 col-xs-offset-1 " >
                  <p> <%= activity.description %></p>
                </div>
                <div id="link-box-button" class="col-xs-2 col-xs-offset-1 ">
                  <%= simple_form_for (@booking) do |f| %>
                    <%= f.hidden_field :user_id, as: :integer, value: activity.user.id %>
                    <%= f.hidden_field :accepted, as: :boolean, value: nil %>
                    <%= f.hidden_field :activity_id, as: :integer, value: activity.id %>
                    <%= f.button :submit, value: "Réserver", class: "btn btn-home", id:"activity-button" %>
                  <% end %>
                  <p><%= link_to 'Détails', activity_path(activity, {search: @search}), class: "btn btn-medium", id:"activity-button" %></p>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="text-center">
      <%= link_to 'Effectuer une autre recherche', pages_home_path, class: "btn btn-danger", id:"btn-center" %>
    </div>
  </div>
</div>


<!--
=======
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <div>
            <ul>
              <% @activities.each do |activity| %>
                <li>
                  <div class="search-card">
                    <div id="flexouille">
                      <div id="text-box">
                        <h4> <%= activity.name %> avec <%= activity.user.name %> <%= activity.user.surname %> </h4>
                        <p> <%= activity.description %></p>
                        <p>Adresse: <%= activity.user.address %> / Compensation: <%= activity.price %>€</p>
                      </div>
                      <%= image_tag "papy_marcel.jpeg", {class: "avatar-square-big"} %>

                    </div>
                    <div id="link-box">
                      <p><%= link_to 'Show', activity_path(activity, {search: @search}), class: "btn btn-primary" %></p>
                      <% end %>
>>>>>>> master -->

app/views/activities/new.html.erb
<%= render 'form' %>

app/views/activities/show.html.erb
<div class="page-wrapper">
  <div class="page-container">
    <h1 class="text-center">Détails de la demande</h1>
    <div class="container">
      <div class="row">
        <div class="card-container text-center">
          <div class="card">
                 <% if @activity.name === "Cuisine" %>
                  <h3 class="text-center"><i class="fa fa-cutlery"></i> <%= @activity.name %></h3>
                <% elsif @activity.name === "Informatique" %>
                  <h3 class="text-center"><i class="fa fa-laptop"></i> <%= @activity.name %></h3>
                <% elsif @activity.name === "Conversation" %>
                  <h3 class="text-center"><i class="fa fa-commenting-o"></i> <%= @activity.name %></h3>
                <% else %>
                  <h3 class="text-center"><i class="fa fa-book"></i> <%= @activity.name %></h3>
                <% end %>
           <div class="col-xs-4 col-sm-4 photo">
              <% if @activity.user.photo? %>
                  <%= cl_image_tag @activity.user.photo.path, width: 150, height: 150, crop: :fill, class: "user_picture_activity"%>
              <% else %>
                <%= image_tag "placeholder-user-photo.png", width: 150, height: 150, crop: :fill, class: "user_picture_activity"%>
              <% end %>
              <p><strong><%= @activity.user.name %> <%= @activity.user.surname %></strong></p>
              </div>
            <div class="col-xs-8  col-sm-8 text-left">
              <div >
                <table class="table_activity">
                  <tbody>
                    <tr>
                      <td class="head"><strong>Détail : </strong></td>
                      <td><%= @activity.description %></td>
                    </tr>
                    <tr>
                      <td class="head"><strong>Date :</strong></td>
                      <td> Du <%= @activity.starting_time %> au <%= @activity.end_time %></td>
                    </tr>
                    <tr>
                      <td class="head"><strong>Rémunération :</strong></td>
                      <td><%= @activity.price %>€</td>
                    </tr>
                    <tr>
                      <% if @activity.user.description %>
                        <td class="head"><strong>A propos de moi :</strong></td>
                        <td><%= @activity.user.description %></td>
                      <% end %>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <%= simple_form_for (@booking) do |f| %>
              <%= f.hidden_field :user_id, as: :integer, value: @activity.user.id %>
              <%= f.hidden_field :accepted, as: :boolean, value: nil %>
              <%= f.hidden_field :activity_id, as: :integer, value: @activity.id %>

              <%= f.button :submit, value: "Réserver", class: "btn btn-home", id: "activity_button" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="text-center">
        <%= link_to 'Retour aux activités', activities_path({search: @search}), class: "btn btn-danger", id:"btn-center" %>
      </div>
  </div>
</div>
</div>

app/views/bookings/index.html.erb
<div class="page-wrapper">
  <div class="page-container">
  <h1 class="text-center title">Mes rendez-vous</h1>
    <div class="container">
      <div class="row">
        <% @my_bookings.each do |my_booking| %>

          <div class="col-xs-8 col-xs-offset-2 ">
            <div class="booking">
              <% if my_booking.user.photo? %>
                <%= cl_image_tag my_booking.user.photo.path, width: 200, height: 200, crop: :fill, class: "booking-index-image" %>
              <% else %>
                <%= image_tag "placeholder-user-photo.png", width: 200, height: 200, crop: :fill, class: "booking-index-image"%>
              <% end %>
              <div class='booking-body'>
                <div>
                  <%= link_to activity_path(my_booking.activity.id) do %>
                    <h3><%= my_booking.activity.name %></h3>
                  <% end %>
                  <p>Du <%= my_booking.activity.starting_time %> au <%= my_booking.activity.end_time %> </p>
                  <p><strong>Vous serez aidé par:</strong> <%= my_booking.user.name %></p>
                </div>
                <div id="acceptance">
                  <% if my_booking.accepted.nil? %>
                    <%= simple_form_for (my_booking) do |f| %>
                      <%= f.hidden_field :accepted, as: :boolean, value: true %>
                      <%= f.button :submit, value: "Accepter", class: "btn btn-success"%>
                    <% end %>
                    <%= simple_form_for (my_booking) do |f| %>
                      <%= f.hidden_field :accepted, as: :boolean, value: false %>
                      <%= f.button :submit, value: "Refuser", class: "btn btn-danger"%>
                    <% end %>
                  <% end %>
                </div>
                <div>
                  <% if my_booking.accepted.nil? %>
                    <h4>En attente</h4>
                  <% elsif my_booking.accepted %>
                    <h4>Accepté</h4>
                  <% else %>
                    <h4>Refusé</h4>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>




      <% @bookings.each do |booking| %>
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2 ">
            <%= link_to activity_path(booking.activity.id) do %>

              <div class="booking">
                <% if booking.activity.user.photo? %>
                  <%= cl_image_tag booking.activity.user.photo.path, width: 200, height: 200, crop: :fill, class: "booking-index-image" %>
                  <% else %>
                     <%= image_tag "placeholder-user-photo.png", width: 200, height: 200, crop: :fill, class: "booking-index-image"%>
                  <% end %>
                <div class='booking-body'>
                  <div>
                    <h3><%= booking.activity.name %></h3>
                    <p>Du <%= booking.activity.starting_time %> au <%= booking.activity.end_time %> </p>
                    <p><strong>Vous irez aider:</strong> <%= booking.activity.user.name %></p>

                  </div>
                  <div>
                    <% if booking.accepted.nil? %>
                      <h4>En attente</h4>
                    <% elsif booking.accepted %>
                      <h4>Accepté</h4>
                    <% else %>
                      <h4>Refusé</h4>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %> <!-- linkto -->
          </div>
        </div>
      <% end %>
        <div class="text-center">
          <%= link_to 'Retourner à mon profil', user_path(current_user), class: "btn btn-danger", id:"btn-center" %>
        </div>


    </div>
  </div>
</div>
<%# link_to 'See all activities', activities_path %>

app/views/bookings/new.html.erb
<div class="page-wrapper">
  <div class="page-container">
    <div class="container">
      <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
          <%= simple_form_for (@booking) do |f| %>
            <%= f.error_notification %>
            <%= f.input :user_id, as: :integer, value: :user_id %>
            <%= f.hidden_field :accepted, as: :boolean, value: :false %>
            <%= f.input :activity_id, as: :integer, value: :activity_id %>

            <%= f.button :submit, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<ul>
  <li><h3><%= @booking.user.name %> <%= @booking.user.surname %></h3></li>
  <li><p><%= @booking.user.address %></p></li>
  <li><p><%= @booking.activity.name %></p></li>
  <li><p><%= @booking.activity.description %></p></li>
  <li><p><%= @booking.activity.starting_time %></p></li>
  <li><p><%= @booking.activity.end_time %></p></li>
  <li><p><%= @booking.activity.price %></p></li>
  <li><p><%= @booking.accepted %></p></li>
</ul>

<%= link_to 'See all bookings', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Adopte un Senior</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= cloudinary_js_config %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/notices' %>
<%= render 'shared/navbar' %>

<%= yield %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/pages/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Adopte un senior</h1>
    <h3>Aide des personnes agées dans leur quotidien</h2>
<!--     <h3>Sois rémunéré pour ton temps, en argent ou en petites attentions</h3>
 -->    <%= render 'shared/searchform' %>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'banner'%>

app/views/shared/_footer.html.erb
<div class="footer-basic-centered">
      <h3 class="footer-company-name">Adopte Un Senior &copy; 2016</p>
      <p class="footer-company-moto">Aide des personnes agées dans leur quotidien
</p>

</div>
    </div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>



  <div class="navbar-wagon">
    <!-- Logo -->

    <%= link_to root_path do %>
      <i class="fa fa-heartbeat"> Adopte un senior</i>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Text link -->
    <%# link_to "Recherche une activité", root_path, class: "btn btn-home" %>
       <%= link_to "Demander de l'aide",  new_activity_path, method: "get", class: "btn btn-home", id:"btn-navbar" %>

   <%= link_to "Mes rendez-vous", bookings_path, method: "get", class: "btn btn-home", id:"btn-navbar" %>

      <!-- Text link -->
<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>
 -->
      <!-- Text link -->
<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">L'équipe</a>
 -->
       <!-- Notification link-->
<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
      </a> -->

<!-- Button (call-to-action) -->
<!--       <a href="" class="navbar-wagon-item navbar-wagon-button btn">Rejoins une activité</a> -->

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">

          <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Mon profil", user_path(current_user), method: "get" %></li>
            <li><%= link_to "Me déconnecter", destroy_user_session_path, method: "delete" %></li>
          </ul>
        </div>
      </div>
    </div>


    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Mon profil", user_path(current_user), method: "get" %></li>
          <li><%= link_to "Modifier mon profil", edit_user_path(current_user), method: "get" %></li>
          <li><%= link_to "Mes activités", user_path(current_user), method: "get" %></li>
          <li><%= link_to "Mes rendez-vous", bookings_path, method: "get" %></li>
          <li><%= link_to "Me déconnecter", destroy_user_session_path, method: "delete" %></li>
        </ul>
      </div>
    </div>
  </div>



<% else %>



 <div class="navbar-wagon">
    <!-- Logo -->

    <%= link_to root_path do %>
      <i class="fa fa-heartbeat"> Adopte un senior</i>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">


<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">Concept</a>
 -->
    <!-- Text link -->
    <%= link_to "Recherche une activité", root_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Text link -->
<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>
 -->
      <!-- Text link -->
<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">L'équipe</a>
 -->

      <!-- Button (call-to-action) -->
      <%= link_to "Créer un compte", new_user_registration_path, {class: "btn btn-home"} %>


      <%= link_to "Connecte toi", new_user_session_path, {class: "btn btn-home"} %>
    </div>

    <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Créer un compte", new_user_registration_path%></li>
          <li><%= link_to "Connecte toi", new_user_session_path %></li>
        </ul>
      </div>
    </div>
  </div>


<% end %>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_searchform.html.erb
<div class="search-bar">
<div class="form-inline">
<%= simple_form_for :search, url: activities_path, method: 'get' do |f| %>
  <%= f.input :name, collection: ["Cuisine", "Informatique", "Conversation", "Lecture"], prompt: "Choisir une activité", label: false%>
  <%= f.input :starting_time, as: :string, placeholder: 'Date de début',input_html: { class: 'datepicker'}, label: false %>
  <%= f.input :end_time, as: :string, placeholder: 'Date de fin', input_html: { class: 'datepicker'}, label: false %>
  <%= f.input :address, placeholder: 'Entrer une adresse', label: false %>
  <%= f.submit "Trouver", class: "btn btn-home", label: false %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="page-wrapper">
  <div class="page-container page-container-responsive row-space-top-4 row-space-8r">
    <div class="container">
      <div class="row">
        <div class="col-xs-4">
          <div class="user-div">
            <div class="pict-cont">
              <% if @user.photo? %>
                <%= cl_image_tag @user.photo.path, width: 225, crop: :fill, class: "user-picture" %>
              <% else %>
                <%= image_tag 'placeholder-user-photo.png', width: 225, crop: :fill, class: "user-picture" %>
              <% end %>
            </div>
            <div class="user-info">
                  <table>
                    <tbody>
                      <% if @user.name && @user.surname %>
                        <tr>
                          <td class="field-name"><p><strong>Nom: </strong></p></td>
                          <td><p><%= @user.name %> <%= @user.surname %></p></td>
                        </tr>
                      <% end %>
                      <% if @user.birthdate %>
                            <tr>
                              <td class="field-name"><p><strong>Age: </strong></p></td>
                              <td><p><%= Date.today.year - @user.birthdate.to_i %></p></td>
                            </tr>
                      <% end %>
                      <% if @user.address %>
                            <tr>
                              <td class="field-name"><p><strong>Adresse: </strong></p></td>
                              <td><p><%= @user.address %></p></td>
                            </tr>
                      <% end %>
                      <% if @user.description %>
                            <tr>
                              <td class="field-name"><p><strong>Détails: </strong></p></td>
                              <td><p><%= @user.description %></p></td>
                            </tr>
                      <% end %>
                    </tbody>
                  </table>
              <div class="text-center">
              <% if @user === current_user %>
              <%= link_to "Modifier mon profil", edit_user_path(current_user), method: "get", class: "btn btn-home btn-center" %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-1"></div>
        <div class="col-xs-7">
          <div class="activity-div">
            <h1><%= "Bonjour, je m'appelle #{@user.name} !" %></h1>
            <h3>J'ai besoin d'aide pour</h3>
              <table>
                <body>
                  <% @user.activities.each do |activity| %>
                    <tr>
                      <td>
                        <% if activity.name === "Cuisine" %>
                          <p><i class="fa fa-cutlery"> </i> <%= activity.name %></p>
                        <% elsif activity.name === "Informatique" %>
                          <p><i class="fa fa-laptop"> </i> <%= activity.name %></p>
                        <% elsif activity.name === "Conversation" %>
                          <p><i class="fa fa-commenting-o"> </i> <%= activity.name %></p>
                        <% else %>
                          <p><i class="fa fa-book"> </i> <%= activity.name %></p>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to "Voir", activity_path(activity), method: "get", class: "btn btn-default Un" %>
                      </td>
                      <% if @user === current_user %>
                        <td>
                          <%= link_to "Modifier", edit_activity_path(activity), method: "get", class: "btn btn-default" %>
                        </td>
                        <td>
                          <%= link_to "Supprimer", activity_path(activity), method: "delete", class: "btn btn-default"  %>
                        </td>
                      <% end %>
                    </tr>
                  <% end %>
                </body>
              </table>
          </div>
        </div>
        <div class="text-center">
            <%= link_to "Ajouter une activité", new_activity_path, method: "get", class: "btn btn-home", id:"button-profile" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>